### ISSUE TITLE
Number range expression is not compiled accordingly

### ISSUE THREAD

**Issue by dm4t2** [bublejs/buble#252] opened 2020-04-18 20:00 UTC
`[...Array(10).keys()]` compiles to `[].concat( Array(10).keys() )` which returns not the expected array `[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]`. Instead the compiled expression returns `[Array Iterator]`.

**Comment by mourner** [comment] 2020-05-29 07:29
Duplicate of #131

**Closed by mourner** 2020-05-29 07:29 UTC
